### ISSUE TITLE
Beware Symfony 3.x!

### ISSUE THREAD

**Issue by gander** [flint/flint#31] opened 2015-12-11 14:54 UTC
`composer require flint/flint:~1.0`:

```
flint/flint              1.7.1   Enhanced Silex
flint/tacker             0.6.0   Easy configuration based on Symfony Config
pimple/pimple            v1.1.1  Pimple is a simple Dependency Injection Container for PHP 5.3
psr/log                  1.0.0   Common interface for logging libraries
silex/silex              v1.3.4  The PHP micro-framework based on the Symfony Components
symfony/config           v3.0.0  Symfony Config Component
symfony/debug            v3.0.0  Symfony Debug Component
symfony/event-dispatcher v3.0.0  Symfony EventDispatcher Component
symfony/filesystem       v3.0.0  Symfony Filesystem Component
symfony/http-foundation  v3.0.0  Symfony HttpFoundation Component
symfony/http-kernel      v3.0.0  Symfony HttpKernel Component
symfony/routing          v3.0.0  Symfony Routing Component
twig/twig                v1.23.1 Twig, the flexible, fast, and secure template language for PHP
```

``` html
Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' with message 'None of the routers in the chain matched url "/"' in vendor/flint/flint/src/Flint/Routing/ChainMatcher.php:85
Stack trace:
#0 vendor/flint/flint/src/Flint/Routing/ChainMatcher.php(56): Flint\Routing\ChainMatcher->doMatch('/')
#1 vendor/silex/silex/src/Silex/LazyUrlMatcher.php(51): Flint\Routing\ChainMatcher->match('/')
#2 vendor/symfony/http-kernel/EventListener/RouterListener.php(103): Silex\LazyUrlMatcher->match('/')
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 vendor/symfony/event-dispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKerne in vendor/symfony/http-kernel/Controller/ControllerResolver.php on line 122
```

Proper composer install:
`composer require flint/flint:~1.0 symfony/http-kernel:~2.3 symfony/config:~2.3`

So far, only so much I noticed , but there may be more problems. I suggest you install all components of the write ~2.3 instead of >=2.3

**Comment by henrikbjorn** [comment] 2015-12-14 08:33
@gander thanks for opening this ticket, do you have an example application or small code example where it doesn't work?

**Comment by gander** [comment] 2015-12-15 11:51
Example: http://eternal-santana-3000.codio.io/

**Comment by henrikbjorn** [comment] 2015-12-15 14:57
@gander So the issue is that the pretty exception page is gone?

**Comment by henrikbjorn** [comment] 2015-12-15 15:01
Ahh i see. The conversion from exception to http exception aren't happening.

**Comment by gander** [comment] 2015-12-16 08:46
Yes.

**Comment by henrikbjorn** [comment] 2015-12-16 10:22
Fixed in master, could you please verify my own testing, before i tag a new release.

**Comment by gander** [comment] 2015-12-16 10:58
Look http://eternal-santana.codio.io:3000/ it's working! Great!

**Closed** 2015-12-16 11:55 UTC
